# Generated by Django 5.0.2 on 2024-03-17 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FetchedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('cash_flow', models.BigIntegerField()),
                ('total_debt', models.BigIntegerField()),
                ('cash', models.BigIntegerField()),
                ('growth_1_3', models.FloatField()),
                ('growth_4_10', models.FloatField()),
                ('beta', models.FloatField()),
                ('shares_outstanding', models.BigIntegerField()),
                ('stated_at', models.DateField(verbose_name='date of the financial statements')),
            ],
        ),
    ]
