# Generated by Django 5.0.2 on 2024-03-18 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountedCashflowData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operating_cashflow', models.BigIntegerField()),
                ('total_debt', models.BigIntegerField()),
                ('cash_and_shortterm_investment', models.BigIntegerField()),
                ('eps_growth_projection_1y', models.FloatField()),
                ('eps_growth_projection_5y', models.FloatField()),
                ('beta', models.FloatField()),
                ('shares_outstanding', models.BigIntegerField()),
                ('stated_at', models.DateField(verbose_name='date of the financial statements')),
                ('intrinsic_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('company_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='FetchedData',
        ),
        migrations.AddField(
            model_name='discountedcashflowdata',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock'),
        ),
    ]
